name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: ./script/arch.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to docker.io
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ikrong
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@v4.1.1
      with:
         context: .
         file: Dockerfile.arch
         platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/386
         push: true
         tags: ikrong/mini-http:${{github.ref_name}}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          token: ${{ secrets.TOKEN }}
          files: |
             dist/*.tar.gz
             dist/*.zip
