name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:

  build:
    if: ${{ startsWith("refs/tags", github.ref) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: ./script/arch.sh
      
    # - name: Login to docker.io
    #   uses: docker/login-action@v2
    #   with:
    #     registry: docker.io
    #     username: ikrong
    #     password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Build
      uses: docker/build-push-action@v4.1.1
      with:
         file: Dockerfile.arch
         platforms: darwin/amd64,darwin/arm64,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/386,windows/386,windows/amd64,windows/arm/v7
         push: true
         tags: ikrong/mini-http:${{github.ref_name}}
