name: Test

on:
  push:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to docker.io
              uses: docker/login-action@v2
              with:
                  registry: docker.io
                  username: ikrong
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Login to Aliyuncs
              uses: docker/login-action@v2
              with:
                  registry: registry.cn-beijing.aliyuncs.com
                  username: ${{ secrets.ALIYUN_USERNAME }}
                  password: ${{ secrets.ALIYUN_PASSWORD }}
            - name: Run Test
              shell: bash
              run: |
                  go test -v .
            - name: Test Build
              uses: docker/build-push-action@v4.0.0
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ikrong/mini-http:beta
                      registry.cn-beijing.aliyuncs.com/ikrong/mini-http:beta
